"""Stage 8 — quality filtering.

Computes line/character metrics for every record and applies flag-based
filtering: minified code, generated code, vendored dependencies, binary-ish
content, giant data blobs, repeated/spam content, oversized lockfiles.

Useful infrastructure files (Dockerfiles, CI/CD configs, database
migrations, package manifests, Terraform, nginx/server configs, k8s
manifests) are on a keep-list that exempts them from length-based drops —
they are legitimate long-line/low-entropy files — while still passing
through secret scanning and binary checks.

Which flags drop vs. merely annotate is fully config-driven
(quality.drop_flags / quality.flag_only).

Performance shape: all content-derived signals for a record are computed in
one pure function (`_content_signals`) — one splitlines, one C-level regex
pass for the alnum ratio (bit-identical to the old per-character loop: \\w
matches exactly str.isalnum() plus underscore), one slice per bounded head —
optionally on the processing.cpu_workers process pool. Flag decisions,
drops and stats stay in the parent, so results are identical to serial.
"""

from __future__ import annotations

import posixpath
import re
from functools import partial

from ucc.constants import RT_CODE
from ucc.parallel import parallel_map, resolve_cpu_workers
from ucc.processing.base import ShardContext, Stage

_VENDOR_PATH_RX = re.compile(
    r"(^|/)(node_modules|bower_components|vendor|vendors|third[_\-]?party|"
    r"external|externals|\.yarn|jspm_packages|dist|build|out|target/release|"
    r"target/debug|site-packages|\.eggs)(/|$)",
    re.IGNORECASE,
)
_MINIFIED_PATH_RX = re.compile(r"\.min\.(js|css)$|\.(bundle|pack)\.js$", re.IGNORECASE)
_GENERATED_MARKER_RX = re.compile(
    r"(?i)\b(do not edit|code generated by|auto-?generated|automatically generated|"
    r"this file (was|is) generated|@generated|generated by protoc|lint:disable autogenerated)\b"
)
_GENERATED_PATH_RX = re.compile(r"(_pb2(_grpc)?\.py|\.pb\.go|\.g\.(cs|dart)|_generated\.[a-z]+)$")

_LOCKFILE_BASENAMES = {
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock",
    "cargo.lock", "gemfile.lock", "composer.lock", "go.sum", "flake.lock",
    "packages.lock.json", "podfile.lock",
}

# Keep-list: always-useful engineering files, exempt from length-based drops.
_KEEP_BASENAME_RX = re.compile(
    r"(?i)^(Dockerfile[^/]*|docker-compose[^/]*\.ya?ml|Makefile|CMakeLists\.txt|"
    r"Jenkinsfile|nginx[^/]*\.conf|package\.json|pyproject\.toml|setup\.py|"
    r"requirements[^/]*\.txt|go\.mod|Cargo\.toml|pom\.xml|build\.gradle(\.kts)?|"
    r"Chart\.yaml|values\.ya?ml|kustomization\.ya?ml|Procfile|Vagrantfile|"
    r"\.gitlab-ci\.ya?ml|schema\.(sql|prisma))$"
)
_KEEP_PATH_RX = re.compile(
    r"(^|/)\.github/workflows/[^/]+\.ya?ml$|\.(tf|tfvars)$"
    r"|(^|/)(migrations?|db/migrate)/[^/]+\.sql$",
    re.IGNORECASE,
)

_BASE64_RUN_TEMPLATE = r"[A-Za-z0-9+/=]{%d,}"
_OBFUSCATION_RX = re.compile(
    r"(eval|exec|Function)\s*\(\s*(atob|base64|b64decode|fromCharCode|chr)", re.IGNORECASE
)

# Everything str.isalnum() counts (\w == isalnum + underscore) plus the
# code-punctuation set below — one C-level pass instead of a per-character
# Python loop over up to 200 KB per record.
_NON_ALNUM_RX = re.compile(r"[^\w(){}\[\];:=<>+\-*/.,'\"# \n\t]")

# Flags length-exempted for keep-listed files.
_LENGTH_FLAGS = {"minified", "low_alnum", "repeated_content", "too_large", "data_blob_heavy"}

_BLOB_RX_CACHE: dict[int, re.Pattern] = {}


def _blob_rx(base64_run: int) -> re.Pattern:
    rx = _BLOB_RX_CACHE.get(base64_run)
    if rx is None:
        rx = re.compile(_BASE64_RUN_TEMPLATE % base64_run)
        _BLOB_RX_CACHE[base64_run] = rx
    return rx


def _is_kept_engineering_file(path: str | None) -> bool:
    if not path:
        return False
    base = posixpath.basename(path)
    return bool(_KEEP_BASENAME_RX.match(base) or _KEEP_PATH_RX.search(path))


def _content_signals(item: tuple[str, bool], base64_run: int) -> tuple:
    """Pure per-record signal extraction (process-pool worker).

    item = (content, is_code). Returns only scalars:
    (line_count, max_line_length, total_line_length, alnum_count, sample_len,
     stripped_len, has_nul, replacement_char_count, generated_marker,
     obfuscation, blob_chars, unique_line_count)
    """
    content, is_code = item
    lines = content.splitlines() or [""]
    line_count = len(lines)
    lens = list(map(len, lines))
    max_len = max(lens)
    total_len = sum(lens)

    sample = content[:200_000]
    alnum = len(sample) - len(_NON_ALNUM_RX.findall(sample))

    head = content[:100_000]
    has_nul = "\x00" in head
    repl_count = head.count("�")
    stripped_len = len(content.strip())

    gen_marker = False
    obfuscation = False
    blob_chars = 0
    unique_lines = 0
    if is_code:
        gen_marker = _GENERATED_MARKER_RX.search(content[:2000]) is not None
        obfuscation = _OBFUSCATION_RX.search(head) is not None
        blob_chars = sum(
            m.end() - m.start() for m in _blob_rx(base64_run).finditer(content)
        )
        if line_count > 200:
            unique_lines = len(set(lines))

    return (line_count, max_len, total_len, alnum, len(sample), stripped_len,
            has_nul, repl_count, gen_marker, obfuscation, blob_chars, unique_lines)


def compute_metrics(rec: dict) -> None:
    """Stamp line/character metrics onto a record (shared helper)."""
    line_count, max_len, total_len, alnum, sample_len, *_ = _content_signals(
        (rec["content"], False), 0
    )
    rec["line_count"] = line_count
    rec["max_line_length"] = max_len
    rec["avg_line_length"] = round(total_len / line_count, 2)
    rec["alnum_ratio"] = round(alnum / max(sample_len, 1), 4)


class QualityFilterStage(Stage):
    name = "quality_filter"

    def run(self, rows: list[dict], ctx: ShardContext) -> list[dict]:
        qcfg = ctx.cfg.quality
        drop_flags = set(qcfg.get("drop_flags") or [])
        min_chars = int(qcfg.get("min_content_chars", 2))
        max_bytes = int(qcfg.get("max_content_bytes", 1_048_576))
        minified_avg = float(qcfg.get("minified_avg_line_len", 250.0))
        minified_max = int(qcfg.get("minified_max_line_len", 10_000))
        base64_run = int(qcfg.get("max_base64_run", 2048))
        repeated_ratio = float(qcfg.get("repeated_line_ratio", 0.10))
        min_alnum = float(qcfg.get("min_alnum_ratio", 0.20))
        lockfile_max = int(qcfg.get("lockfile_max_bytes", 204_800))
        cpu_workers = resolve_cpu_workers(ctx.cfg.path("processing.cpu_workers", 1))

        signals = parallel_map(
            partial(_content_signals, base64_run=base64_run),
            [(rec["content"], rec["record_type"] == RT_CODE) for rec in rows],
            cpu_workers,
        )

        out: list[dict] = []
        live = ctx.progress("quality_filter", total=len(rows))
        for rec, sig in zip(rows, signals):
            live.update()
            (line_count, max_len, total_len, alnum, sample_len, stripped_len,
             has_nul, repl_count, gen_marker, obfuscation, blob_chars,
             unique_lines) = sig
            rec["line_count"] = line_count
            rec["max_line_length"] = max_len
            rec["avg_line_length"] = round(total_len / line_count, 2)
            rec["alnum_ratio"] = round(alnum / max(sample_len, 1), 4)

            content: str = rec["content"]
            path = rec.get("path") or ""
            base = posixpath.basename(path).lower() if path else ""
            flags = set(rec.get("quality_flags") or [])
            kept_file = _is_kept_engineering_file(path)
            is_code = rec["record_type"] == RT_CODE

            if has_nul or (
                len(content) > 0 and repl_count / min(len(content), 100_000) > 0.02
            ):
                flags.add("binary_like")
            if stripped_len < min_chars:
                flags.add("empty")
            if rec["size_bytes"] > max_bytes:
                flags.add("too_large")

            if is_code:
                if path and _MINIFIED_PATH_RX.search(path):
                    flags.add("minified")
                elif (
                    rec["avg_line_length"] > minified_avg
                    or rec["max_line_length"] > minified_max
                ) and rec.get("language") not in ("JSON", "Markdown", None):
                    flags.add("minified")
                if path and _VENDOR_PATH_RX.search(path):
                    flags.add("vendored")
                if path and _GENERATED_PATH_RX.search(path):
                    flags.add("generated_metadata")
                if gen_marker:
                    flags.add("generated_marker")
                if rec["alnum_ratio"] < min_alnum:
                    flags.add("low_alnum")
                if obfuscation:
                    flags.add("suspicious_obfuscation")

                if base in _LOCKFILE_BASENAMES:
                    flags.add("lockfile")
                    if rec["size_bytes"] > lockfile_max:
                        flags.add("lockfile_large")

                if blob_chars:
                    flags.add("data_blob")
                    if blob_chars / max(len(content), 1) > 0.5:
                        flags.add("data_blob_heavy")

                if line_count > 200:
                    if unique_lines / line_count < repeated_ratio:
                        flags.add("repeated_content")

            for flag in flags:
                ctx.bump(f"quality.flag.{flag}")

            fatal = flags & drop_flags
            if kept_file:
                fatal -= _LENGTH_FLAGS
            if fatal:
                ctx.exclude(rec, "quality", detail=",".join(sorted(fatal)))
                continue

            rec["quality_flags"] = sorted(flags)
            out.append(rec)

        live.close()
        ctx.bump("quality.records_out", len(out))
        ctx.log.info("quality_filter: %d -> %d", len(rows), len(out))
        return out
